import 'bootstrap';
import {navBar} from './navbar';
import {dailyTasks} from './dailytasks';
import {urgentTasks} from './urgent';
import {render} from './render';
import {tasks} from './task';
import {addDailyTask} from './addtask';
tasks();
navBar();
dailyTasks();
addDailyTask();
const dailyButton = document.getElementById("daily");
dailyButton.addEventListener("click",render);
dailyButton.addEventListener("click",dailyTasks);
const urgentButton = document.getElementById("urgent");
urgentButton.addEventListener("click",render);
urgentButton.addEventListener("click",urgentTasks);
const addDailyTaskButton = document.getElementById("addDailyTask");
addDailyTaskButton.addEventListener("click",addDailyTask);